DATASET: 'xian'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'vit_b'
SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'
PATCH_SIZE: 256
BATCH_SIZE: 32
DATA_WORKER_NUM: 1
TRAIN_EPOCHS: 30
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 128
TOPONET_VERSION: 'normal'

#################### MODIFICATION START ####################
# CONTRASTIVE LEARNING
CONTRASTIVE_EMBED_DIM: 128 # Embedding dimension for contrastive learning
GRAPH_EMBED_DIM: 256 # Embedding dimension for graph representation

# Graph Transformer (GT) settings
GT_D_MODEL: 256  # Transformer depth
GT_N_HEADS: 4    # Attention heads
GT_N_LAYERS: 3   # Transformer layers
#################### MODIFICATION END ####################

# Inference
INFER_BATCH_SIZE: 64
SAMPLE_MARGIN: 0
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.1949462890625, P=0.34380707144737244 R=0.326823890209198 F1=0.3351004719734192
# ======= road ======
# Best threshold 0.3408203125, P=0.6585257053375244 R=0.7146456837654114 F1=0.6854389309883118
# ======= topo ======
# Best threshold 0.705078125, P=0.9746968150138855 R=0.9701263904571533 F1=0.9724062085151672

ITSC_THRESHOLD: 0.195
ROAD_THRESHOLD: 0.195
TOPO_THRESHOLD: 0.705
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16